### ISSUE TITLE
Componentização da aplicação

### ISSUE THREAD

**Issue by Isaac-alencar** [Isaac-alencar/react-challenge-notes#11]
## Contexto
So far so good, fizemos uns pequenos ajustes pontuais em funções javascript, sem muitos problemas. Agora vamos tocar em um assunto muito divertido e bem popular no react, que são componentes. 

vamos refatorar a aplicação e aplicar alguns patterns (padões) que são bem úteis construção de componentes.

essa issue é bem importante, uma vez que os componentes são a base das aplicações react e por tanto, aplicar um bom design de codigo é muito importante, para construirmos softwares que podem escalar e evoluírem melhor com o tempo.

## Tarefa
- [x]  refatorar o componente layout completamente, extrair o maximo de componente possíveis. **atenção**, para isso é importante entender o que é um componente e para saber onde extrair cada componente;
- [x] estudar sobre context api no react. apenas estudar, não vamos trabalhar ainda com ela

**Comment by andre-fsantos** [comment]
Consegui visualizar apenas o `NoteForm` para extração. Pensei em mover as funções `getNotes`, `addNote`, `editNote` e `deleteNote` para fora do Layout, mas essas funções possuem variáveis de estado que são necessárias ao componente Layout.

**Comment by Isaac-alencar** [comment]
> Consegui visualizar apenas o `NoteForm` para extração. Pensei em mover as funções `getNotes`, `addNote`, `editNote` e `deleteNote` para fora do Layout, mas essas funções possuem variáveis de estado que são necessárias ao componente Layout.

Concordo, não tem tantos componentes assim pra extrair, mas acho que a fins de estudo você pode criar um componente `NotesList` que recebe uma lista de notas e retorna um componente `Note`, pra isso eu sugiro como referência sugiro usar o [renderProp](https://pt-br.react.dev/reference/react/cloneElement#passing-data-with-a-render-prop) pattern vai ajudar a clarear as ideias

quanto as funções para serem removidas, elas entrarão na segunda parte, que envolve você estudar a context api. beleza?
